import type { Metadata } from "next";
import { Geist, Geist_Mono, M_PLUS_1p, Inter } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const Mplus1p = M_PLUS_1p({
  variable: "--font-mplus-1p",
  weight: ["400", "500", "700"],
  subsets: ["latin"]
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

const isProd = process.env.NODE_ENV === 'production';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <base href={isProd ? "/new-portfolio/" : ""}/>
      </head>
      <body className={`
        ${geistSans.variable} ${geistMono.variable} ${Mplus1p.variable} ${inter.variable}
        antialiased
      `}>
        {children}
      </body>
    </html>
  );
}
